In [1]:
import numpy as np

# For reproducibility
np.random.seed(0)

# ----- Activation Function and Derivative -----
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(x):
    """Derivative of sigmoid wrt its input (pre-activation)"""
    s = sigmoid(x)
    return s * (1 - s)

# ----- Input and True Output -----
x = np.array([[0.5, 0.2]])   # (1, 2)
y = np.array([[1]])          # (1, 1)

# ----- Weight Initialization -----
# Hidden layer: 2 inputs → 2 hidden neurons
w1 = np.random.rand(2, 2)    # (2, 2)
b1 = np.random.rand(1, 2)    # (1, 2)

# Output layer: 2 hidden → 1 output
w2 = np.random.rand(2, 1)    # (2, 1)
b2 = np.random.rand(1, 1)    # (1, 1)

# Learning rate
lr = 0.1

# ----- Forward Pass -----
# Hidden layer
a1 = np.dot(x, w1) + b1      # pre-activation (1, 2)
z1 = sigmoid(a1)             # activation (1, 2)

# Output layer
z2 = np.dot(z1, w2) + b2     # pre-activation (1, 1)
y_hat = sigmoid(z2)          # prediction (1, 1)

# ----- Loss -----
loss = 0.5 * (y_hat - y)**2

# ----- Backpropagation (Chain Rule) -----
# dL/dy_hat
dL_dy = (y_hat - y)

# Output layer derivatives
dy_dz2 = sigmoid_deriv(z2)
dL_dz2 = dL_dy * dy_dz2

dL_dw2 = np.dot(z1.T, dL_dz2)  # (2, 1)
dL_db2 = dL_dz2                # (1, 1)

# Backprop to hidden layer
dL_dz1 = np.dot(dL_dz2, w2.T) * sigmoid_deriv(a1)  # (1, 2)

dL_dw1 = np.dot(x.T, dL_dz1)    # (2, 2)
dL_db1 = dL_dz1                 # (1, 2)

# ----- Parameter Update -----
w2 -= lr * dL_dw2
b2 -= lr * dL_db2
w1 -= lr * dL_dw1
b1 -= lr * dL_db1

# ----- Output -----
print("\nUpdated Parameters:")
print("W1:\n", w1)
print("b1:\n", b1)
print("W2:\n", w2)
print("b2:\n", b2)

print("Old loss:", float(loss))
new_y_hat = sigmoid(np.dot(sigmoid(np.dot(x, w1)+b1), w2)+b2)
new_loss = 0.5 * (new_y_hat - y)**2
print("New loss:", float(new_loss))



Updated Parameters:
W1:
 [[0.54887781 0.71530426]
 [0.6027891  0.54492914]]
b1:
 [[0.42378341 0.64612389]]
W2:
 [[0.43854751]
 [0.89281445]]
b2:
 [[0.96504659]]
Old loss: 0.00791496218853424
New loss: 0.00787494313962682


C:\Users\enasa\AppData\Local\Temp\ipykernel_784\2228551227.py:73: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("Old loss:", float(loss))
C:\Users\enasa\AppData\Local\Temp\ipykernel_784\2228551227.py:76: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("New loss:", float(new_loss))
